import os
import sys
import yaml
import subprocess
import re

try:
    import inquirer
except ImportError:
    print("\033[91m[System Error] 'inquirer' package not found. Please run 'pip install -r requirements.txt' first.\033[0m")
    sys.exit(1)

DEBUG_MODE = False  # Development mode: When True, native commands will not be executed, only printed.

def load_config(yaml_path="projects.yaml"):
    if not os.path.exists(yaml_path):
        print(f"\033[91m[System Error] Configuration file not found: {yaml_path}\033[0m")
        sys.exit(1)
    with open(yaml_path, 'r', encoding='utf-8') as f:
        try:
            return yaml.safe_load(f)
        except yaml.YAMLError as e:
            print(f"\033[91m[System Error] Error parsing YAML: {e}\033[0m")
            sys.exit(1)

def print_system_msg(msg):
    print(f"\033[92m[System Status] {msg}\033[0m")

def print_warning_msg(msg):
    print(f"\033[93m[System Prompt] {msg}\033[0m")

def print_error_msg(msg, suggestion=""):
    print(f"\033[91m[System Error] {msg}\033[0m")
    if suggestion:
        print(f"\033[93m[Debugging Suggestion]\n{suggestion}\033[0m")

def generate_commands(project, chipyard_dir):
    makefile_dir = project['makefile_dir']
    hw_config = project['hw_config']
    is_debug = project.get('is_debug', False)
    compile_cmd = project.get('compile_cmd')
    binary_name = project.get('binary_name', 'output.riscv')
    
    # Prefix for loading the environment
    source_env = f"source {chipyard_dir}/env.sh"
    
    # Construct software compilation command
    if compile_cmd:
        cmd_sw_compile = f"{source_env} && cd {makefile_dir} && {compile_cmd}"
    else:
        cmd_sw_compile = f"{source_env} && make -C {makefile_dir}"

    # Construct hardware simulation command
    if is_debug:
        cmd_hw_sim = f"{source_env} && cd {chipyard_dir}/sims/verilator && make run-binary-debug CONFIG={hw_config} BINARY={makefile_dir}/{binary_name}"
    else:
        cmd_hw_sim = f"{source_env} && cd {chipyard_dir}/sims/verilator && make run-binary CONFIG={hw_config} BINARY={makefile_dir}/{binary_name}"
        
    return cmd_sw_compile, cmd_hw_sim

def run_native_command(cmd, step_name):
    print(f"\n\033[96m================ Start Execution: {step_name} ================\033[0m")
    if DEBUG_MODE:
        print_warning_msg(f"Currently in development simulation mode (DEBUG_MODE=True), skipping actual execution.")
        print(f"Native command: {cmd}")
        return True

    try:
        # Execute native command, stdout/stderr will stream directly to the terminal
        process = subprocess.Popen(cmd, shell=True, executable='/bin/bash')
        process.wait()
        
        if process.returncode != 0:
            print_error_msg(f"{step_name} failed (Exit Code: {process.returncode})",
                            f"Please copy the following command and execute it manually in the terminal to debug:\n$ {cmd}")
            return False
        return True
    except Exception as e:
        print_error_msg(f"Unexpected error while executing subprocess: {e}")
        return False

def export_to_script(cmd_sw, cmd_hw):
    script_content = f"""#!/bin/bash
# This script is automatically generated by Chipyard Runner
# Please ensure you have loaded the conda environment and env.sh before executing

echo "[Script] Starting software compilation..."
{cmd_sw}
if [ $? -ne 0 ]; then
    echo "Software compilation failed, aborting script."
    exit 1
fi

echo "[Script] Starting hardware simulation..."
{cmd_hw}
"""
    script_name = "run_task.sh"
    with open(script_name, "w", encoding='utf-8') as f:
        f.write(script_content)
    # If on Linux/Mac, change file permissions to executable
    if os.name == 'posix':
        os.chmod(script_name, 0o755)
    
    print_system_msg(f"Successfully exported script to: {os.path.abspath(script_name)}")
    print_warning_msg(f"You can execute it manually by typing ./{script_name}")

def parse_cycles(log_text):
    # Try to extract cycles from various possible log formats
    hw_match = re.search(r'\[HW\].*cycles=(\d+)', log_text)
    if hw_match: return int(hw_match.group(1))
    
    sw_match = re.search(r'Cycles consumed:\s*(\d+)', log_text)
    if sw_match: return int(sw_match.group(1))
    
    sw_match2 = re.search(r'\[SW\].*cycles=(\d+)', log_text)
    if sw_match2: return int(sw_match2.group(1))
    
    return None

def compare_simulation_results(projects, chipyard_dir):
    print("\n\033[96m================ Performance Comparison Report ================\033[0m")
    # Expand paths starting with ~ to absolute paths to prevent read failures
    chipyard_path = os.path.expanduser(chipyard_dir)
    results = []

    for p in projects:
        # Skip advanced debugging options used specifically for generating waveforms
        if p.get('is_debug', False):
            continue

        hw_config = p['hw_config']
        binary_name = p.get('binary_name', 'output.riscv')
        # Verilator redirects standard output to a file with the .log extension
        log_name = binary_name.replace('.riscv', '.log')
        
        log_path = os.path.join(
            chipyard_path, 
            "sims", "verilator", "output", 
            f"chipyard.harness.TestHarness.{hw_config}", 
            log_name
        )
        
        print(f"\033[90m[Fetching Data] Attempting to read: {log_path}\033[0m")
        
        if not os.path.exists(log_path):
            print(f"\033[93m  -> [Not Executed] File not found. This indicates the implementation has not been simulated yet.\033[0m\n")
            results.append((p['name'], "N/A (Not Executed)"))
            continue
            
        with open(log_path, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
            
        cycles = parse_cycles(content)
        if cycles is not None:
            print(f"\033[92m  -> Successfully extracted Cycles: {cycles:,}\033[0m\n")
            results.append((p['name'], f"{cycles:,} Cycles"))
        else:
            print(f"\033[91m  -> Parsing failed. No cycle records found in the log.\033[0m\n")
            results.append((p['name'], "Parsing Failed (Invalid Log Format)"))

    # Output summary table
    print("\n\033[96m================ Performance Summary Table ================\033[0m")
    print(f"{'Implementation Scheme':<45} | {'Execution Cycles'}")
    print("-" * 65)
    for name, cycles in results:
        print(f"{name:<45} | {cycles}")
    print("-" * 65)

    # Architectural difference analysis
    print("\n\033[93m[Architectural Performance Analysis]\033[0m")
    print("1. Pure C (Software): Sequentially executed by CPU ALU, constrained by instruction fetch, decode, and branch overheads.")
    print("2. RoCC (Tightly Coupled): Directly integrated into the CPU pipeline with extremely low communication latency. Suitable for compute-intensive tasks with small data sizes.")
    print("3. DMA (Loosely Coupled): Accesses memory directly via the system bus. Has bus latency overhead but fully offloads the CPU, making it ideal for bulk data transfers.")
    print("4. RVV (Vector Extension): Performs data-level parallel computation using standard SIMD instructions. Offers low software development cost and is excellent for array and matrix processing.")
    print("\n* Note on Data Volume: The RVV architecture test processes 256 parallel LFSR streams")
    print("  simultaneously, whereas other architectures process a single stream. This difference")
    print("  in computation volume is intentionally designed to showcase RVV's parallel acceleration capability.")
    print("==================================================\n")


def print_stage_info(stage, current_path, input_desc, input_path, config_desc, config_path, output_desc, output_path, next_stage):
    print(f"\n\033[95m--------------------------------------------------\033[0m")
    print(f"1. Current Stage: {stage}")
    print(f"   - Path: {current_path}")
    print(f"2. Required Input Target File: {input_desc}")
    print(f"   - Path: {input_path}")
    print(f"3. Config File: {config_desc}")
    print(f"   - Path: {config_path}")
    print(f"4. Output File: {output_desc}")
    print(f"   - Path: {output_path}")
    print(f"5. Next Stage: {next_stage}")
    print(f"\033[95m--------------------------------------------------\033[0m\n")

def main():
    print_system_msg("Welcome to the Chipyard Interactive Automation Testing Tool")
    if DEBUG_MODE:
        print_warning_msg("Currently in local development simulation mode, no actual compilation will be executed.")
    
    config = load_config()
    projects = config.get('projects', [])
    chipyard_dir = config.get('global_settings', {}).get('chipyard_dir', '../chipyard')

    if not projects:
        print_error_msg("No projects defined in projects.yaml.")
        return

    # Create menu options
    choices = []
    
    # Extension: Add the special feature to compare simulation results
    choices.append(("[Generate Performance Report] Automatically fetch and compare execution results for all implementations", "compare_results"))
    
    for p in projects:
        # Display name and description in the menu to facilitate learning
        display_text = f"{p['name']} ({p['description']})"
        choices.append((display_text, p))

    questions = [
        inquirer.List('selected_project',
                      message="Please select a feature or test project to execute (Use UP/DOWN arrows, press Enter to confirm)",
                      choices=choices,
                      )
    ]
    
    answers = inquirer.prompt(questions)
    if not answers:
        print("\nCancelled.")
        return

    selected_project = answers['selected_project']
    
    # If the user selects the comparison report, enter the dedicated flow and exit
    if selected_project == "compare_results":
        compare_simulation_results(projects, chipyard_dir)
        return
        
    # Display knowledge base
    if 'knowledge_base' in selected_project:
        print(f"\n\033[96m[Note] {selected_project['knowledge_base']}\033[0m")
    
    # Generate commands
    cmd_sw, cmd_hw = generate_commands(selected_project, chipyard_dir)
    
    print("\n\033[93m[Prompt] This tool is about to execute the following two native commands in the background:\033[0m")
    print("-" * 60)
    print(f"1. (Software Compilation) $ {cmd_sw}")
    print(f"2. (Hardware Simulation) $ {cmd_hw}")
    print("-" * 60)
    
    confirm_q = [
        inquirer.List('action',
                      message="Confirm the next action",
                      choices=[
                          ('Start Execution', 'run'),
                          ('Export as Shell Script (Do Not Execute)', 'export'),
                          ('Cancel', 'cancel')
                      ])
    ]
    
    action_ans = inquirer.prompt(confirm_q)
    if not action_ans or action_ans['action'] == 'cancel':
        print("\nExecution cancelled.")
        return
        
    if action_ans['action'] == 'export':
        export_to_script(cmd_sw, cmd_hw)
    elif action_ans['action'] == 'run':
        makefile_dir = os.path.expanduser(selected_project['makefile_dir'])
        binary_name = selected_project.get('binary_name', 'output.riscv')
        hw_config = selected_project['hw_config']
        c_file = binary_name.replace('.riscv', '.c')
        
        # Step 1: Software Compilation
        print_stage_info(
            stage="Software Compilation",
            current_path=makefile_dir,
            input_desc="C Source Code",
            input_path=os.path.join(makefile_dir, c_file),
            config_desc="Makefile / Linker Script",
            config_path=os.path.join(makefile_dir, "Makefile"),
            output_desc="RISC-V Executable Binary",
            output_path=os.path.join(makefile_dir, binary_name),
            next_stage="Hardware Simulation"
        )
        
        success = run_native_command(cmd_sw, "Software Compilation")
        if not success:
            sys.exit(1)
            
        # Step 2: Hardware Simulation
        sim_dir = os.path.join(os.path.expanduser(chipyard_dir), "sims", "verilator")
        log_name = binary_name.replace('.riscv', '.log')
        out_dir = os.path.join(sim_dir, "output", f"chipyard.harness.TestHarness.{hw_config}")
        
        print_stage_info(
            stage="Hardware Simulation",
            current_path=sim_dir,
            input_desc="RISC-V Executable Binary",
            input_path=os.path.join(makefile_dir, binary_name),
            config_desc="Chipyard SoC Config",
            config_path=f"chipyard.harness.TestHarness.{hw_config}",
            output_desc="Simulation Log",
            output_path=os.path.join(out_dir, log_name),
            next_stage="Finish"
        )
        
        success = run_native_command(cmd_hw, "Hardware Simulation")
        if not success:
            sys.exit(1)
            
        print_system_msg("All tasks executed successfully!")

if __name__ == "__main__":
    main()
